import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Localization service for managing app language (ES/EN) with reactive updates
class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  static const String _languageKey = 'app_language';
  String _currentLanguage = 'ES';

  String get currentLanguage => _currentLanguage;
  bool get isSpanish => _currentLanguage == 'ES';
  bool get isEnglish => _currentLanguage == 'EN';

  /// Initialize and load saved language preference
  Future<void> initialize() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_languageKey) ?? 'ES';
    notifyListeners();
  }

  /// Change language and persist preference
  Future<void> setLanguage(String language) async {
    if (language != 'ES' && language != 'EN') return;
    if (_currentLanguage == language) return;

    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, language);
    notifyListeners();
  }

  /// Get translated text by key
  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  /// Translation dictionary
  static const Map<String, Map<String, String>> _translations = {
    'ES': {
      // Login/Registration Screen
      'login_title': 'Iniciar Sesión',
      'register_title': 'Registrarse',
      'email_label': 'Correo Electrónico',
      'email_hint': 'correo@ejemplo.com',
      'password_label': 'Contraseña',
      'password_hint': '••••••••',
      'confirm_password_label': 'Confirmar Contraseña',
      'remember_me': 'Recordarme',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'login_button': 'Iniciar Sesión',
      'register_button': 'Crear Cuenta',
      'select_role': 'Selecciona tu rol',
      'role_client': 'Cliente',
      'role_client_desc': 'Reserva servicios de transporte',
      'role_admin': 'Administrador',
      'role_admin_desc': 'Gestiona servicios y usuarios',
      'or_continue_with': 'O continúa con',
      'passwords_no_match': 'Las contraseñas no coinciden',
      'account_created': 'Cuenta creada exitosamente',

      // Client Dashboard
      'welcome': 'Bienvenido',
      'current_location': 'Ubicación actual',
      'loading_location': 'Cargando ubicación...',
      'services': 'Servicios',
      'recent_bookings': 'Reservas Recientes',
      'view_all': 'Ver Todo',
      'no_bookings': 'No hay reservas recientes',
      'car_rental': 'Alquiler de Coches',
      'personal_transport': 'Transporte Personal',
      'driver_tracking': 'Seguimiento de Conductor',
      'quick_quote': 'Cotización Rápida',
      'jetskit': 'Jetskit',
      'event_tickets': 'Entradas de Eventos',
      'flights': 'Vuelos',
      'ratings_reviews': 'Ratings & Reviews',
      'confirmed': 'Confirmado',
      'pending': 'Pendiente',
      'in_progress': 'En Progreso',
      'completed': 'Completado',
      'cancelled': 'Cancelado',
      'rebook': 'Reservar de Nuevo',
      'my_rewards': 'Mis Recompensas',

      // Admin Dashboard
      'admin_dashboard': 'Panel de Administración',
      'dashboard': 'Dashboard',
      'bookings': 'Reservas',
      'analytics': 'Analíticas',
      'users': 'Usuarios',
      'settings': 'Configuración',
      'total_bookings': 'Total Reservas',
      'active_users': 'Usuarios Activos',
      'monthly_revenue': 'Ingresos Mensuales',
      'satisfaction_rate': 'Tasa de Satisfacción',
      'booking_requests': 'Solicitudes de Reserva',
      'all_bookings': 'Todas las Reservas',
      'pending_bookings': 'Pendientes',
      'confirmed_bookings': 'Confirmadas',
      'approve': 'Aprobar',
      'reject': 'Rechazar',
      'view_details': 'Ver Detalles',
      'client_name': 'Nombre del Cliente',
      'service': 'Servicio',
      'date': 'Fecha',
      'time': 'Hora',
      'status': 'Estado',
      'amount': 'Monto',
      'priority': 'Prioridad',
      'high': 'Alta',
      'medium': 'Media',
      'low': 'Baja',
      'urgent': 'Urgente',

      // Personal Transport
      'personal_transport_title': 'Transporte Personal',
      'select_service_type': 'Selecciona el Tipo de Servicio',
      'black': 'BLACK',
      'black_suv': 'BLACK SUV',
      'black_evento': 'BLACK EVENTO',
      'black_por_hora': 'BLACK POR HORAS',
      'premium_service': 'Servicio premium para hasta 4 personas',
      'premium_suv_service': 'Servicio premium SUV para hasta 6 personas',
      'special_events_service': 'Servicio premium para eventos especiales',
      'hourly_service': 'Servicio por horas personalizado',
      'max_persons': 'Máximo',
      'persons': 'personas',
      'base_fare': 'Tarifa base',
      'per_mile': 'por milla',
      'per_minute': 'por minuto',
      'minimum': 'Mínimo',
      'airport_fee': 'Tarifa aeropuerto',
      'pickup_location': 'Ubicación de Recogida',
      'dropoff_location': 'Ubicación de Destino',
      'select_on_map': 'Seleccionar en el mapa',
      'service_date': 'Fecha del Servicio',
      'service_time': 'Hora del Servicio',
      'passenger_count': 'Número de Pasajeros',
      'service_duration': 'Duración del Servicio (horas)',
      'special_requirements': 'Requisitos Especiales',
      'preferred_language': 'Idioma Preferido',
      'spanish': 'Español',
      'english': 'English',
      'airport_service': 'Servicio de Aeropuerto',
      'calculate_price': 'Calcular Precio',
      'estimated_price': 'Precio Estimado',
      'distance': 'Distancia',
      'duration': 'Duración',
      'miles': 'millas',
      'minutes': 'minutos',
      'book_now': 'Reservar Ahora',
      'booking_confirmed': 'Reserva Confirmada',
      'booking_error': 'Error al crear la reserva',

      // Car Rental
      'car_rental_title': 'Alquiler de Autos',
      'find_cars_near_you': 'Encuentra autos cerca de ti',
      'your_location': 'Tu ubicación actual',
      'obtaining_location': 'Obteniendo ubicación...',
      'pickup_place': 'Lugar de recogida',
      'dropoff_place': 'Lugar de devolución',
      'same_pickup_place': 'Mismo lugar de recogida',
      'pickup_date': 'Fecha de recogida',
      'dropoff_date': 'Fecha de devolución',
      'search_available_cars': 'Buscar autos disponibles',
      'all_categories': 'Todas las Categorías',
      'economy': 'Económico',
      'suv': 'SUV',
      'luxury': 'Lujo',
      'sports': 'Deportivo',
      'available': 'Disponible',
      'not_available': 'No Disponible',
      'per_day': 'por día',
      'view_vehicle': 'Ver Vehículo',
      'no_vehicles': 'No hay vehículos disponibles',

      // Driver Tracking
      'driver_tracking_title': 'Seguimiento del Conductor',
      'tracking_your_trip': 'Rastreando tu viaje',
      'driver_info': 'Información del Conductor',
      'driver_name': 'Nombre del Conductor',
      'vehicle': 'Vehículo',
      'license_plate': 'Placa',
      'rating': 'Calificación',
      'call_driver': 'Llamar al Conductor',
      'message_driver': 'Mensaje al Conductor',
      'trip_details': 'Detalles del Viaje',
      'pickup': 'Recogida',
      'destination': 'Destino',
      'estimated_arrival': 'Llegada Estimada',
      'trip_status': 'Estado del Viaje',
      'sos_emergency': 'SOS Emergencia',
      'share_trip': 'Compartir Viaje',

      // Notifications
      'notifications': 'Notificaciones',
      'all_notifications': 'Todas',
      'bookings_notifications': 'Reservas',
      'driver_notifications': 'Conductor',
      'trips_notifications': 'Viajes',
      'promotions': 'Promociones',
      'unread': 'No Leídas',
      'mark_as_read': 'Marcar como Leída',
      'mark_all_read': 'Marcar Todas como Leídas',
      'delete_notification': 'Eliminar Notificación',
      'no_notifications': 'No hay notificaciones',
      'notification_deleted': 'Notificación eliminada',
      'all_marked_read': 'Todas marcadas como leídas',

      // Payments & Invoices
      'payments_invoices': 'Pagos y Facturas',
      'payments': 'Pagos',
      'invoices': 'Facturas',
      'payment_methods': 'Métodos de Pago',
      'transaction_history': 'Historial de Transacciones',
      'add_payment_method': 'Agregar Método de Pago',
      'card_number': 'Número de Tarjeta',
      'expiry_date': 'Fecha de Vencimiento',
      'cvv': 'CVV',
      'cardholder_name': 'Nombre del Titular',
      'set_as_default': 'Establecer como Predeterminado',
      'total_spent': 'Total Gastado',
      'pending_payments': 'Pagos Pendientes',
      'completed_payments': 'Pagos Completados',
      'download_invoice': 'Descargar Factura',
      'payment_successful': 'Pago Exitoso',
      'payment_failed': 'Pago Fallido',
      'invoice_number': 'Número de Factura',
      'issue_date': 'Fecha de Emisión',
      'due_date': 'Fecha de Vencimiento',
      'subtotal': 'Subtotal',
      'tax': 'Impuesto',
      'total': 'Total',

      // Ratings & Reviews
      'ratings_reviews_title': 'Calificaciones y Reseñas',
      'rate_your_trips': 'Califica tus Viajes',
      'my_reviews': 'Mis Reseñas',
      'completed_trips': 'Viajes Completados',
      'rate_trip': 'Calificar Viaje',
      'overall_rating': 'Calificación General',
      'service_quality': 'Calidad del Servicio',
      'vehicle_condition': 'Condición del Vehículo',
      'driver_professionalism': 'Profesionalismo del Conductor',
      'punctuality': 'Puntualidad',
      'cleanliness': 'Limpieza',
      'write_review': 'Escribe una Reseña',
      'add_photos': 'Agregar Fotos',
      'submit_review': 'Enviar Reseña',
      'review_submitted': 'Reseña enviada exitosamente',
      'trip_already_reviewed': 'Este viaje ya tiene una reseña',
      'average_rating': 'Calificación Promedio',
      'total_reviews': 'Total de Reseñas',

      // Settings
      'settings_title': 'Configuración',
      'account_settings': 'Configuración de Cuenta',
      'notification_settings': 'Configuración de Notificaciones',
      'language_settings': 'Idioma',
      'privacy_settings': 'Privacidad',
      'help_support': 'Ayuda y Soporte',
      'about': 'Acerca de',
      'logout': 'Cerrar Sesión',
      'profile': 'Perfil',
      'edit_profile': 'Editar Perfil',
      'change_password': 'Cambiar Contraseña',
      'delete_account': 'Eliminar Cuenta',
      'language': 'Idioma',
      'select_language': 'Seleccionar Idioma',
      'language_changed': 'Idioma cambiado exitosamente',

      // Common
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'search': 'Buscar',
      'filter': 'Filtrar',
      'close': 'Cerrar',
      'yes': 'Sí',
      'no': 'No',
      'ok': 'OK',
      'back': 'Volver',
      'next': 'Siguiente',
      'previous': 'Anterior',
      'submit': 'Enviar',
      'refresh': 'Actualizar',
      'retry': 'Reintentar',
      'select': 'Seleccionar',
      'selected': 'Seleccionado',
      'apply': 'Aplicar',
      'reset': 'Restablecer',
      'clear': 'Limpiar',
      'done': 'Hecho',
    },
    'EN': {
      // Login/Registration Screen
      'login_title': 'Sign In',
      'register_title': 'Sign Up',
      'email_label': 'Email Address',
      'email_hint': 'email@example.com',
      'password_label': 'Password',
      'password_hint': '••••••••',
      'confirm_password_label': 'Confirm Password',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot password?',
      'login_button': 'Sign In',
      'register_button': 'Create Account',
      'select_role': 'Select your role',
      'role_client': 'Client',
      'role_client_desc': 'Book transportation services',
      'role_admin': 'Administrator',
      'role_admin_desc': 'Manage services and users',
      'or_continue_with': 'Or continue with',
      'passwords_no_match': 'Passwords do not match',
      'account_created': 'Account created successfully',

      // Client Dashboard
      'welcome': 'Welcome',
      'current_location': 'Current location',
      'loading_location': 'Loading location...',
      'services': 'Services',
      'recent_bookings': 'Recent Bookings',
      'view_all': 'View All',
      'no_bookings': 'No recent bookings',
      'car_rental': 'Car Rental',
      'personal_transport': 'Personal Transport',
      'driver_tracking': 'Driver Tracking',
      'quick_quote': 'Quick Quote',
      'jetskit': 'Jetskit',
      'event_tickets': 'Event Tickets',
      'flights': 'Flights',
      'ratings_reviews': 'Ratings & Reviews',
      'confirmed': 'Confirmed',
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'rebook': 'Rebook',
      'my_rewards': 'My Rewards',

      // Admin Dashboard
      'admin_dashboard': 'Admin Dashboard',
      'dashboard': 'Dashboard',
      'bookings': 'Bookings',
      'analytics': 'Analytics',
      'users': 'Users',
      'settings': 'Settings',
      'total_bookings': 'Total Bookings',
      'active_users': 'Active Users',
      'monthly_revenue': 'Monthly Revenue',
      'satisfaction_rate': 'Satisfaction Rate',
      'booking_requests': 'Booking Requests',
      'all_bookings': 'All Bookings',
      'pending_bookings': 'Pending',
      'confirmed_bookings': 'Confirmed',
      'approve': 'Approve',
      'reject': 'Reject',
      'view_details': 'View Details',
      'client_name': 'Client Name',
      'service': 'Service',
      'date': 'Date',
      'time': 'Time',
      'status': 'Status',
      'amount': 'Amount',
      'priority': 'Priority',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'urgent': 'Urgent',

      // Personal Transport
      'personal_transport_title': 'Personal Transport',
      'select_service_type': 'Select Service Type',
      'black': 'BLACK',
      'black_suv': 'BLACK SUV',
      'black_evento': 'BLACK EVENTO',
      'black_por_hora': 'BLACK HOURLY',
      'premium_service': 'Premium service for up to 4 people',
      'premium_suv_service': 'Premium SUV service for up to 6 people',
      'special_events_service': 'Premium service for special events',
      'hourly_service': 'Customized hourly service',
      'max_persons': 'Maximum',
      'persons': 'persons',
      'base_fare': 'Base fare',
      'per_mile': 'per mile',
      'per_minute': 'per minute',
      'minimum': 'Minimum',
      'airport_fee': 'Airport fee',
      'pickup_location': 'Pickup Location',
      'dropoff_location': 'Dropoff Location',
      'select_on_map': 'Select on map',
      'service_date': 'Service Date',
      'service_time': 'Service Time',
      'passenger_count': 'Number of Passengers',
      'service_duration': 'Service Duration (hours)',
      'special_requirements': 'Special Requirements',
      'preferred_language': 'Preferred Language',
      'spanish': 'Español',
      'english': 'English',
      'airport_service': 'Airport Service',
      'calculate_price': 'Calculate Price',
      'estimated_price': 'Estimated Price',
      'distance': 'Distance',
      'duration': 'Duration',
      'miles': 'miles',
      'minutes': 'minutes',
      'book_now': 'Book Now',
      'booking_confirmed': 'Booking Confirmed',
      'booking_error': 'Error creating booking',

      // Car Rental
      'car_rental_title': 'Car Rental',
      'find_cars_near_you': 'Find cars near you',
      'your_location': 'Your current location',
      'obtaining_location': 'Obtaining location...',
      'pickup_place': 'Pickup place',
      'dropoff_place': 'Dropoff place',
      'same_pickup_place': 'Same as pickup place',
      'pickup_date': 'Pickup date',
      'dropoff_date': 'Dropoff date',
      'search_available_cars': 'Search available cars',
      'all_categories': 'All Categories',
      'economy': 'Economy',
      'suv': 'SUV',
      'luxury': 'Luxury',
      'sports': 'Sports',
      'available': 'Available',
      'not_available': 'Not Available',
      'per_day': 'per day',
      'view_vehicle': 'View Vehicle',
      'no_vehicles': 'No vehicles available',

      // Driver Tracking
      'driver_tracking_title': 'Driver Tracking',
      'tracking_your_trip': 'Tracking your trip',
      'driver_info': 'Driver Information',
      'driver_name': 'Driver Name',
      'vehicle': 'Vehicle',
      'license_plate': 'License Plate',
      'rating': 'Rating',
      'call_driver': 'Call Driver',
      'message_driver': 'Message Driver',
      'trip_details': 'Trip Details',
      'pickup': 'Pickup',
      'destination': 'Destination',
      'estimated_arrival': 'Estimated Arrival',
      'trip_status': 'Trip Status',
      'sos_emergency': 'SOS Emergency',
      'share_trip': 'Share Trip',

      // Notifications
      'notifications': 'Notifications',
      'all_notifications': 'All',
      'bookings_notifications': 'Bookings',
      'driver_notifications': 'Driver',
      'trips_notifications': 'Trips',
      'promotions': 'Promotions',
      'unread': 'Unread',
      'mark_as_read': 'Mark as Read',
      'mark_all_read': 'Mark All as Read',
      'delete_notification': 'Delete Notification',
      'no_notifications': 'No notifications',
      'notification_deleted': 'Notification deleted',
      'all_marked_read': 'All marked as read',

      // Payments & Invoices
      'payments_invoices': 'Payments & Invoices',
      'payments': 'Payments',
      'invoices': 'Invoices',
      'payment_methods': 'Payment Methods',
      'transaction_history': 'Transaction History',
      'add_payment_method': 'Add Payment Method',
      'card_number': 'Card Number',
      'expiry_date': 'Expiry Date',
      'cvv': 'CVV',
      'cardholder_name': 'Cardholder Name',
      'set_as_default': 'Set as Default',
      'total_spent': 'Total Spent',
      'pending_payments': 'Pending Payments',
      'completed_payments': 'Completed Payments',
      'download_invoice': 'Download Invoice',
      'payment_successful': 'Payment Successful',
      'payment_failed': 'Payment Failed',
      'invoice_number': 'Invoice Number',
      'issue_date': 'Issue Date',
      'due_date': 'Due Date',
      'subtotal': 'Subtotal',
      'tax': 'Tax',
      'total': 'Total',

      // Ratings & Reviews
      'ratings_reviews_title': 'Ratings & Reviews',
      'rate_your_trips': 'Rate Your Trips',
      'my_reviews': 'My Reviews',
      'completed_trips': 'Completed Trips',
      'rate_trip': 'Rate Trip',
      'overall_rating': 'Overall Rating',
      'service_quality': 'Service Quality',
      'vehicle_condition': 'Vehicle Condition',
      'driver_professionalism': 'Driver Professionalism',
      'punctuality': 'Punctuality',
      'cleanliness': 'Cleanliness',
      'write_review': 'Write a Review',
      'add_photos': 'Add Photos',
      'submit_review': 'Submit Review',
      'review_submitted': 'Review submitted successfully',
      'trip_already_reviewed': 'This trip already has a review',
      'average_rating': 'Average Rating',
      'total_reviews': 'Total Reviews',

      // Settings
      'settings_title': 'Settings',
      'account_settings': 'Account Settings',
      'notification_settings': 'Notification Settings',
      'language_settings': 'Language',
      'privacy_settings': 'Privacy',
      'help_support': 'Help & Support',
      'about': 'About',
      'logout': 'Logout',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'delete_account': 'Delete Account',
      'language': 'Language',
      'select_language': 'Select Language',
      'language_changed': 'Language changed successfully',

      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search',
      'filter': 'Filter',
      'close': 'Close',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'submit': 'Submit',
      'refresh': 'Refresh',
      'retry': 'Retry',
      'select': 'Select',
      'selected': 'Selected',
      'apply': 'Apply',
      'reset': 'Reset',
      'clear': 'Clear',
      'done': 'Done',
    },
  };
}
